Feature/add uri healthchecks
keystonejs/keystone-healthchecks pull request #2
Opened 2017-01-31 00:31 UTC by Noviny

2017-02-06 01:19 UTC, Noviny commented
@bassjacob This PR is now ready for review

2017-02-10 02:28 UTC, bassjacob requested changes
case related changes

2017-02-10 02:28 UTC, bassjacob commented on src/healthchecks/canQueryUriFactory.js
> +const canQueryUri = require('./canQueryUri');
Semantically, names of classes should be PascalCase

2017-02-10 02:28 UTC, bassjacob commented on src/index.js
> +		CanQueryUri: require('./healthchecks/CanQueryUri'),
this will fail on any OS that isn't MacOS. The case of the filename is different to the case of the string?

2017-02-10 02:39 UTC, Noviny commented
Fix'd @bassjacob

2017-02-10 03:27 UTC, bassjacob approved these changes

2017-02-10 03:27 UTC, merged